MetaMask/test-dapp

contract.js
Instead of using the `chainId` "3" for the `signTypedData` button (i.e. Ropsten), the test dapp will now use the `chainId` of whichever network is currently selected (falling back to the `networkId` if there is no `chainId`).
This reconciles this repository with the test-dapp in `metamask-extension, which was recently changed: https://github.com/MetaMask/metamask-extension/pull/7859
=> Use current `chainId` for `signTypedData` instead of `3`

contract.js, deploy.sh, package.json
Fixes strange test dapp behavior. It should now be compatible with the old and new inpage providers. I've done basic manual testing with both.
In sum:
- Successfully retrieves Ethereum accounts with new and old inpage providers
- Updates accounts, networkId, and chainId always if possible
- `window.ethereum` -> `ethereum`
- Minor fixes to deploy script and package.json
=> Update test dapp

contract.js
This PR fixes the outstanding lint issue. (We should add the lint to the CI?)
```
yarn run v1.21.1
$ eslint . --ext js,json
metamask-test-dapp/contract.js
117:31  error  'onClickConnect' was used before it was defined  no-use-before-define
✖ 1 problem (1 error, 0 warnings)
```
=> Fix lint issue in contract.js

deploy.sh
I wasn't slicing the shorthash correctly for the `gh-pages` commits. This is now fixed.
=> Fix shorthash in deploy script

index.html
there were two contractStatus spans that were likely remnants from the contract deploy card, which has a status indicator on the different stages the contracts was in. the send and the deploy token don't have any status tracking
=> remove contract status from non contract cards

contract.js
- Call `eth_accounts` on initialization, in case the initial `accountsChanged` is emitted before `DOMContentLoaded`, and therefore before the listener is set up
- This is a general recommendation for dapps, btw (to be added to our docs)
- Change `ethereum.enable()` to `ethereum.send('eth_requestAccounts')`, and handle the returned accounts
- Minor refactoring
=> Update account/initialization handling

package.json
In a moment of poor judgment, I named the start script `serve` instead of `start`. This PR rectifies this mistake.
=> Rename script: serve -> start

package.json
This is an org-scoped package, so adding `publishConfig` to package.json to avoid having to explicitly add `--access=public` to `npm publish`.
=> Add publishConfig to package.json

.eslintrc.js, website/index.js
This PR consolidates the ESLint config into the, er, ESLint config (`.eslintrc.js`)
=> Move all globals into ESLint config

.eslintrc.js, .gitignore, deploy.sh, package.json, website/index.html
Recent work accidentally broke the import of the onboarding bundle when serving the site locally. This PR fixes this by means of a `postinstall` script.
=> Fix locally serving onboarding bundle

website/index.js
Uses `ethereum.request` to make RPC requests instead of the now-deprecated `sendAsync`.
=> Use new EIP 1193 API

deploy.sh
We do actually need to create a temporary dummy commit in order to publish the onboarding bundle (and whatever other scripts we decide to ship with this package).
=> Fix deployment of website scripts

.eslintignore, .eslintrc.js, website/index.html, website/index.js
Adds actions for `rpc-cap` RPC methods:
- `wallet_requestPermissions`
- This method always requests the `eth_accounts` permission
- We can discuss if we want to add buttons with other actions, but we can also manually `ethereum.request` stuff
- `wallet_getPermissions`
Minor fixup
- Delete `.eslintignore`, update `ignorePatterns` in `.eslintrc.js`
=> Add permissions actions

website/index.js
The hosted version of the test dapp was erroneously referencing a forwarder hosted on `localhost`. The `forwarderOrigin` option should only be specified if a non-default forwarder is wanted (e.g. when
testing locally).
=> Only use `localhost` forwarder on `localhost`

deploy.sh
We should clean up the website `.git` folder after deployment.
=> Delete website git folder in deploy script

src/index.js
The `eth-sig-util` import was broken in #63 because it switch from using `require` to `import`. `eth-sig-util` has no default export, so the `sigUtil` variable was getting assigned to `undefined`.
The named export is now used.
=> Fix eth-sig-util import

src/index.html, src/index.js
A `personal_sign` button has been added to test the `personal_sign` method. The results are shown below the button, just as with `signTypedData`.
The `buffer` import is bundled by Webpack automatically, so it didn't require any new dependency or config changes.
=> Add `personal_sign` button

package.json, src/index.js, yarn.lock
This change updates the shared ESLint config to the latest published version, v4.0.0, and fixes one new issue. The `.engines` property has been added to the `package.json` file to ensure that the Node.js-specific rules are targeting the correct version of the runtime.
=> Use @metamask/eslint-config@4.0.0

yarn.lock
This PR updates selfsigned to address a security advisory with its `node-forge` dependency.
For more information see: https://www.npmjs.com/advisories/1561
The `yarn audit` output:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Prototype Pollution in node-forge                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-forge                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 0.10.0                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ webpack-dev-server …
```
=> Use selfsigned@1.10.8

deploy.sh, package.json
Previously `yarn lint` and `yarn build` would get called upon install. I found this to be unnecessary and inconvenient. The `prepare` script that caused this has been replaced with a `prepublishOnly` script, so that it still runs before publish but not upon each install.
The old `prepare` script was also used during deployment, though worryingly we didn't handle the case where it fails. `yarn lint` and `yarn build` are now called separately during the deploy script, and we handle failures for either.
=> Skip lint and build upon install

src/index.js
With the migration to `ethers`, we accidentally broke onboarding. We had assumed that `window.ethereum` was always present.
The initialization steps that use `window.ethereum` have been moved into the `initialization` method, and wrapped in a `try..catch` to ensure te remainder of the intialization proceeds even if MetaMask is not installed.
=> Fix onboarding

webpack.config.js
Sourcemaps are now generated by Webpack and included in the application bundle, both in development and production. This has dramatically increased the size of the bundle (~6x), but given that this dapp is used primarily for development, I think it's worth the cost.
=> Include sourcemaps in bundle

deploy.sh
The `remote` option for the deploy script would not correctly set the remote used for deployment. It is used for everything but the most important step: the deploy step. For the `git push` that ultimately deploys the new build, the remote origin was hard-coded as the MetaMask test dapp repo.
A git command is now used to dynamically fetch the remote URL using the remote name given instead.
=> Fix `remote` option of deploy script

src/index.html, src/index.js
The button should be disabled if MetaMask is not installed, just like every other button.
=> Fix addEthereumChain button disable logic

README.md, deploy.sh
Replaces references to `master` with `main` following default branch renaming.
=> Replace 'master' references with 'main'

deploy.sh, package.json, yarn.lock
This PR updates our deployment script to use the [`gh-pages` package](https://www.npmjs.com/package/gh-pages) for deployment, and removes a lot of complexity from it.
I tested deployment once from `main`, and `gh-pages` returned successfully, although without updating anything because the website content hadn't changed.
I decided to keep `deploy.sh` for the dirty working tree check and the fancy commit message. Otherwise it could've easily fit in a `package.json` script.
=> Use gh-pages package for deployment

yarn.lock
Bumps `ssri` in the lockfile to resolve a security vulnerability.
=> Bump ssri from 8.0.0 to 8.0.1

src/index.js
A simple change that expands coverage of types that chainID might be input as for signTypedMessage call, call with chainID as int remains covered by the  signTypedDataV3.onclick() method in tests. Would have prevented [this regression in 9.6.0](https://github.com/MetaMask/metamask-extension/issues/11308)
=> make chainId string in one test for increased type coverage

src/index.html, src/index.js
Adds this button but only makes it visible when the network supports EIP-1559
https://user-images.githubusercontent.com/4448075/123334988-75a37280-d509-11eb-90ac-8da063579ec1.mov
=> add EIP1559 tx button

src/index.js
The previous message was not compilant with EIP712 and was rejected by
the GridPlus Lattice. The `message` key names must map to the `Mail`
object definitions.
=> Fixes signTypedData_v3 message

src/index.html, src/index.js
Added new form for send transaction as per:
https://github.com/MetaMask/test-dapp/issues/128
=> Add a transaction creation form so that a tx with any parameters can be created #128

src/alert-red.svg, src/index.css, src/index.html, src/index.js
Fixes: https://github.com/MetaMask/test-dapp/issues/56
If a user uses Test Dapp on Mainnet, a warning will be shown.
https://user-images.githubusercontent.com/92310504/140482045-8ecc435c-0e95-4f44-b7b8-37cfb43a1f9c.mp4
=> Warn users when using Test Dapp on Mainnet

src/index.js
Explanation: Fixes an issue where the Send screen in MM would show 1500 TST instead of 1.5 TST after calling Watch Asset 
Manual testing steps:
1) Click Connect
2) Click Create Token in the Send Tokens section
3) Click Add Token to Wallet
4) Click Transfer Tokens
=> Send Tokens flow

src/index.js
We should make this send to the user's own address, not to [a known hacked address that gets swept](https://etherscan.io/address/0x2f318C334780961FB129D2a6c30D0763d9a5C970). It's so scary that we were suggesting 3 eth transactions to a hacked address in our test dapp!
As a short term patch, I am directing this to the team account.
=> Do not send to hacked address, and send 0 eth.

src/index.js
Using load event ensures that `window.ethereum` is always available in global scope when we access provider.
=> Fix event used for accessing provider

src/index.html, src/index.js
**Explanation:**
Fixes: https://github.com/MetaMask/test-dapp/issues/160
Updates the test dapp to consume a query string parameter that describes a deployed contracts address, such as `http://localhost:9011/?contract=0x7F775B6392f46Cf717aBB204557f64F68eB388c1`
This change will allow us to;
- avoid repeatedly deploying a contract when testing (manual testing)
- deploy a contract in the test setup instead of via the browser in the test steps (e2e tests)
**More information:**
- The contract address in the query string param will be applied to all contracts
- You can override the contract address for a specific contract by deploying it
**Before:**
After refreshing the page, there's no way to interact with the deployed contract
https://user-images.githubusercontent.com/53189696/175405985-4c510f …
=> Contract already deployed

src/index.html, src/index.js
Add the following methods:
- setApprovalForAll (unsets the approval for an address, preventing the transfer of all NFTs)
=> revoke NFT allowances

src/index.html, src/index.js
Add the following methods:
- setApprovalForAll (sets/unset the approval for an address to transfer all NFTs)
Test Dapp (Add Set Approval For All & Revoke button to the ERC 1155 section)
setApprovalForAll - true
setApprovalForAll - false
=> Set approval for all erc1155

src/index.html, src/index.js
**What**: in this PR we are introducing a specific Typed Data V4 signature: Permit. According to the [specs for EIP-2612,](https://eips.ethereum.org/EIPS/eip-2612) the signature will have a data type `Permit` with the following data fields:
```
"message": {
"owner": owner,
"spender": spender,
"value": value,
"nonce": nonce,
"deadline": deadline
}
```
https://user-images.githubusercontent.com/54408225/222073236-79861434-79e9-4a42-8587-1559f4ee5d2f.mp4
- Fixes https://github.com/MetaMask/metamask-extension/issues/17941
**How**: 
- the first part of the work, and the scope of this PR, consists in introducing a Permit signature.
- a future PR will take care of importing an ERC20 Permit contract which implements the permit signature, and complete the flow by adding the functionality of …
=> Introducing Permit Signature

src/index.html, src/index.js
**Context**: several issues have been reported related to sending ERC20 tokens with 0 decimals or certain value of decimals.
- https://github.com/MetaMask/metamask-extension/issues/17839
- https://github.com/MetaMask/metamask-extension/issues/18139
**What**: this PR adds the ability to input the desired amount of decimals for the ERC20 token (between 0 and 18). This way we will be able to manually test ERC20 tokens with certain problematic decimal values, like 0.
**How**:
- It has been observed that, that we used to pass a value `4` for the decimals in the contract constructor. However this value does not really have an effect on the token contract - it's always 4 decimals, no matter if we change it to another value. This means that the contract must have hard-coded this value …
=> Adding an input for ERC20 token decimals

.eslintrc.js, README.md, src/index.html, src/request.html, src/request.js, webpack.config.js
We now have a page for making requests directly with query string parameters. For example, you can make an `eth_getLogs` request by navigation to:
`[test dapp path]/request.html?method=eth_getLogs&params=[{}]`
This can be useful for testing RPC methods not covered by the test dapp functionality, or for e2e testing (especially on mobile, where clicking elements on the page can be challenging).
=> Add page for making a request with query parameters

CHANGELOG.md, package.json
The changelog was formatted incorrectly in a few different ways:
* Various links to GitHub were mistakenly prefixed with `git+` because that's the style of link used in the `repository` field in `package.json`. The `auto-changelog` tool isn't compatible with that format, so it has been updated to use an HTTPS link. All changelog links have been fixed as well.
* The link for v6 was missing.
* The "Unreleased" section was missing.
=> Fix changelog formatting

src/index.js
Support the `scrollTo` URL parameter to automatically scroll to an element ID after loading the page.
Required to support E2E tests in mobile as the testing framework (Detox) does not yet support direct interaction with the browser in iOS.
=> Support URL parameter to scroll to element on load

src/index.js
`tokenId` param for `wallet_watchAsset` should be type 'string'. 
Related issue: https://github.com/MetaMask/MetaMask-planning/issues/853
Related PR: https://github.com/MetaMask/metamask-extension/pull/19738
=> Fix NFT tokenId type

CHANGELOG.md, package.json
- Fix issue where add watch NFT buttons introduced in `v7.0.0` called `wallet_watchAsset` with parameter tokenId typed as a number, rather than as a string ([#241](https://github.com/MetaMask/test-dapp/pull/241))
=> Release v7.0.1

CHANGELOG.md, package.json
- Fix XSS vulnerability on the `contract` query string parameter ([#248](https://github.com/MetaMask/test-dapp/pull/248))
=> Release v7.0.2

src/index.html, src/index.js
After the Watch NFT function has been added, we can see how button elements are created whenever we mint NFTs. I.e. minting 30 NFTs would correspond to create 30 watch NFT buttons.
This can be inefficient in terms of UI.
With this PR, we can watch the NFT by its id (instead of generating the long list of buttons).
If you minted 30 NFTs, you would get 30 buttons, for watching each individual asset.
You can Watch the NFT by inputting its id, instead of getting a long list of buttons (corresponding to each id)
=> Watch NFT by id instead of generating a watch NFT button for each token id

src/index.js
Previously, the `chainChanged` event was being used as the network ID value. This is incorrect, as chain ID and network ID values may not match and are not guaranteed to be interchangeable. This PR fixes this issue by:
* using the `chainChanged` event to update both chainId and networkId 
* listening to the `networkChanged` event to update both chainId and networkId
*  note that `networkChanged` is deprecated, but there is no other way to **guarantee** we don't miss a network ID change
=> Fix Network ID incorrectly using chainId value

src/index.html, src/index.js
This PR:
- Adds Malicious Set Approval For All button
- Adds token symbols to PPOM buttons
note: We are not adding Malicious ERC721 Transfer because the user would need to hold an asset of the specific punk collection in order for the simulation to detect potential loses.
=> feat: Add PPOM setApprovalForAll button. Add token symbols for PPOM buttons

src/index.html, src/index.js
Adds ability to create multiple tokens and watch all of them. Shouldn't effect other token methods, they will use the latest created token address for approval and transfers.
For context: https://github.com/MetaMask/MetaMask-planning/issues/1407
=> Adds ability to create multiple tokens and watch all of them.

CHANGELOG.md, package.json
- Fix clickable PPOM section after connecting ([#267](https://github.com/MetaMask/test-dapp/pull/267))
=> Release Candidate v7.3.1

src/index.html, src/index.js
This PR adds the ability to perform `transferFrom` function calls, and do the complete flow (from approve to transfer from) dynamically to the desired addresses.
Notice the ERC20 token already had `transferFrom` and `approve` support, so there is no need to change anything on the contract level.
- The default address for the `approve` input is the one that was previously hardcoded. The reason for that is because this way, we don't need to change any existing e2e tests relying on approving to that address. You can change the address just by entering a different input
- The `transferFrom` addresses can be changed dynamically with an input element
- The `approve` amount is still hardcoded, as this can be changed from the UI if desired
- The `transferFrom` amount is hardcoded, as there is no …
=> feat: add `transferFrom` and `approve` to input address for ERC20 contract

src/index.html, src/index.js
Add the following methods:
- wallet_watchAsset (ERC1155)
Test Dapp
Extension
=> wallet_watchAsset for ERC1155

package.json, webpack.config.js, yarn.lock
The signing examples were broken as of the update to Webpack v5 (#264). The "verification" button for the signatures relies upon the Node.js `assert` and `stream` APIs. Polyfills have been added for both of these.
Additionally, the `assert` polyfill itself relies upon the Node.js `process` API, and expects `process` to be a global. A polyfill has been added for `process`, and it has been set as a global.
=> Fix signing

.github/workflows/build-lint-test.yml, .yarnrc.yml, package.json, yarn.lock
The `@lavamoat/allow-scripts` integration was not setup correctly.
* The `@lavamoat/preinstall-always-fail` package was missing, despite being referenced in the configuration
* Various packages had their install scripts allowed, but they were not necessary and they failed when run.
* The `allow-scripts` step was not run in CI
All of these issues have been resolved.
=> Fix allow-scripts integration

src/index.js
The example `eth_signTypedData_v4` message has been updated to include a field that can reproduce this bug: https://github.com/MetaMask/metamask-mobile/issues/7792 That signing bug results in invalid signatures for any messages that include a `bytes` field with the value `0x`.
=> Update `eth_signTypedData_v4` example

src/index.html, src/index.js
Adds `wallet_revokePermissions` for `eth_accounts` button under the Permissions Actions card.
https://github.com/MetaMask/test-dapp/assets/13376180/ba2b3196-b37e-42b2-bba3-68703e6a47d5
=> Add wallet_revokePermissions for eth_accounts

src/index.js
We will add support to more chains in the ppom feature [here](https://github.com/MetaMask/metamask-extension/pull/22070/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519). For that, we need a way to test the malicious signatures in different chains.
Currently is not possible, as the malicious signature data is hardcoding the chain id 1 (Mainnet)
This PR changes the malicious signature data, by updating the chainId dynamically with the current chainId. This allows us to trigger the malicious signatures in different chains.
**Note**: the Malicious Trade Order is only flagged on Mainnet, and we will need to update this signature data once Blockaid provides us with another signature valid for all chains. This will come in a future PR.
- Localhost (this branch …
=> fix: make malicious signatures chain agnostic

src/index.js, src/onchain-sample-contracts.js
The PPOM module now is supported in more networks. For that reason, we need to update the transactions in order to point to the correct contract addresses according to the network we have selected.
The Trade Order signature also needs to be changed, as the previous one was not flagged in all networks.
Notice for seeing the Malicious warning, you need to have some balance, for paying the gas for the transactions, and a small amount of the ERC20 token for the Transfer transaction, on each chain.
Pending (in progress)
https://github.com/MetaMask/test-dapp/assets/54408225/5d6b45aa-5a71-4eb4-b00a-7be6c0618ac0
=> add: support malicious tx's in multiple networks

CHANGELOG.md, package.json
This is the release candidate PR for `v8.1.0`
- Add support for ppom malicious transactions in multiple networks ([#281](https://github.com/MetaMask/test-dapp/pull/281))
- Add support for ppom malicious signatures in multiple networks ([#279](https://github.com/MetaMask/test-dapp/pull/279))
- Add `wallet_revokePermissions` for `eth_accounts` ([#278](https://github.com/MetaMask/test-dapp/pull/278))
=> Release Candidate v8.1.0

src/index.html, src/index.js
This PR adds different malformed typed signatures.
Note, at the moment, clicking most of them results in breaking MetaMask
This uncovers the following bugs on Extension:
- [[Bug]: Signatures - Verify 3rd party details disappears if an empty domain is passed on a Typed Signature 3 & 4](https://github.com/MetaMask/metamask-extension/issues/21011)
- [[Bug]: Signatures - MetaMask breaks with the error Invalid primary type definition](https://github.com/MetaMask/metamask-extension/issues/22899)
- [[Bug]: Signatures - MetaMask breaks with error msg.map is not a function when passing an invalid type](https://github.com/MetaMask/metamask-extension/issues/22525)
- [[Bug]: Signatures - Passing extra data not typed is added in the signature but not visible on the …
=> Add Malformed Signatures

src/index.html, src/index.js
This PR adds the following functionalitites in the test dapp:
- Add x10 transactions in batch
- Add x10 transactions in queue
- Add x10 signatures in batch
- Add x10 signatures in queue
Note: both the transaction and the signature are malicious, meaning that we are able not only to test the batch/queue functionalities for the transaction controller but also the ppom validations under this stress circumstances.
This has uncovered the following issues:
- https://github.com/MetaMask/metamask-extension/issues/23225
- https://github.com/MetaMask/metamask-extension/issues/23222
- https://github.com/MetaMask/metamask-mobile/issues/8770
- https://github.com/MetaMask/metamask-mobile/issues/8771
and help find a way to reproduce these 2:
- https://github.com/MetaMask/metamask-extension/issues/23173 …
=> feat: add batch and queue signature and transactions

src/index.js
Fix missing try/catch blocks for Send Batch/Queue. This was causing to see a different behaviour between Send and Signature Requests. Thanks to @cryptotavares to point out the mistake.
The 2 issues are now closed:
- https://github.com/MetaMask/metamask-extension/issues/23225
- https://github.com/MetaMask/metamask-mobile/issues/8770
https://github.com/MetaMask/test-dapp/assets/54408225/e1841e98-2b5f-4769-a055-e6979c85079a
1. Trigger Queue Transactions
2. Accept one -- see next one appears
3. Accept another one -- see next one appears
4. Reject one -- see next one appears
Now do the same with Signatures, and see that the result is exactly the same.
=> fix: adds missing try catch for Send

src/index.html, src/index.js, src/onchain-sample-contracts.js
This PR adds support for testing malicious transactions and signatures on Sepolia.
Note: for the ERC20 transfer, if you do not own any tokens, the validation will fail. For testing this specific case, I've added a Mint button above (only for Sepolia) which allows you to mint tokens. After minting, trying the ERC20 malicious transfer should successfully validate that as malicious.
https://github.com/MetaMask/test-dapp/assets/54408225/84970827-1203-491e-8c8e-00e905d648ba
Testing malicious tx and signatures:
1. Select Sepolia
2. Try Malicious Send Eth
3. Mint some ERC2 tokens
4. Try Malicious Send ERC
5. Try Malicious Approval
6. Try Set Approval for all
7. Try all the signatures
Testing mint button
1. Select Sepolia and refresh --> see Mint button is there
2. Select another network and …
=> feat: add malicious tx and signatures for sepolia

src/index.js
`window.ethereum.selectedAddress` was recently [removed from provider](https://github.com/MetaMask/providers/pull/306) after a deprecation period. This PR replaces a reference to that property with a local value instead to fix a broken E2E spec in [extension](https://github.com/MetaMask/metamask-extension/pull/23375)
=> Use accounts variable instead of provider.selectedAddress

CHANGELOG.md, package.json
- Replace deprecated `window.ethereum.selectedAddress` property with local account value ([#300](https://github.com/MetaMask/test-dapp/pull/300))
=> Release candidate v8.3.0

src/index.html, src/index.js
As part of [#2224](https://github.com/MetaMask/MetaMask-planning/issues/2224), we need to have a way to test whether the token allowance to transfer tokens is exceeded or not. This change shows the error message on the token addresses text box so that it can be asserted against in e2e tests.
=> Adds transferFromTokens error to token addresses text box

src/index.html, src/index.js
Similarly to the [Add Malformed Signatures PR](https://github.com/MetaMask/test-dapp/pull/290), in this PR we are adding Malformed Transactions. It consists on the following:
- Invalid Value Type (String): transaction with a string passed as the Value param
- Invalid Transaction Type (Not Supported): transaction with a non supported tx type. This uncovers the following bug 
- [[Bug]: Transaction with invalid/unsupported type cannot be cleared from the wallet and remains as Unapproved](https://github.com/MetaMask/metamask-extension/issues/23180)
- Send With Odd Hex Data: this uncovered the following issue, now resolved (both Extension and Mobile)
- [[Extension] Confirmations - PPOM - Bypassing the Malicious Warning and turning into Request May not be …
=> Add Malformed Transactions

CHANGELOG.md, package.json
This is the release candidate for v8.4.0.
**Added:**
- Add Malformed Transactions ([#295](https://github.com/MetaMask/test-dapp/pull/295))
- Adds transferFromTokens error to token addresses text box ([#304](https://github.com/MetaMask/test-dapp/pull/304))
- Add Increase Token Allowance btn ([#302](https://github.com/MetaMask/test-dapp/pull/302))
=> Release candidate v8.4.0

CHANGELOG.md, package.json
This is the release candidate for v8.5.0.
(We update the version earlier than usual to provide an opportunity for everyone to test on the Base chain.)
**Added:**
- Add Base network support [#310](https://github.com/MetaMask/test-dapp/pull/310)
=> Release candidate v8.5.0

src/index.js
The network status field would show the `networkId` on load (in decimal), but after switching chains it would show the `chainId` (in hex). It now shows the `networkId` in all cases.
This means re-introducing the deprecated `networkChanged` event listener, but this listener is still something we want to be able to test.
=> fix: Fix network status field

src/index.html, src/index.js
This PR adds support for querying the `allowance(address owner, address spender) → uint256` function for ERC20 tokens.
This will enable testing more effectively the Approve and Increase Allowance functionalities.
https://github.com/MetaMask/test-dapp/assets/54408225/4f8d18ba-f02f-431b-bc8e-7f1f5fdb7e41
1. Deploy an ERC20 token contract
2. Add owner and spender addresses
3. Click get allowance
4. Perform an approve or increase allowance to the same spender and owner
5. Click get allowance
6. See how the amount changed
=> feat: add get allowance support for ERC20 tokens

src/index.html, src/index.js
This PR adds support to Deeplinks in the test dapp. This will allows us to automate e2e tests around the feature. Specifically,
- Adds Simple Send Eth for deeplinks
- Adds ERC20 transfer. For this, we need to pass the contract address and the decimals in the URL. Notice for this functionality we'll access it from the browser (outside the wallet), that's why we need to pre-deploy a contract, in order to use it, if we want to have assets.
- Adds ERC20 approve. For this, we need to pass the contract address and the decimals in the URL. Notice for this functionality we'll access it from the browser (outside the wallet), that's why we need to pre-deploy a contract, in order to use it, if we want to have assets.
https://github.com/MetaMask/test-dapp/assets/54408225/723e133e-9cb6-4422-b4c1-764e1c …
=> feat: add deeplinks for Send Eth, Send ERC20 and Approve ERC20

CHANGELOG.md, package.json
This is the release candidate for v8.6.0.
Added:
- add deeplinks for Send Eth, Send ERC20 and Approve ERC20 ([#313](https://github.com/MetaMask/test-dapp/pull/313))
- update Base NFT contract address ([#315](https://github.com/MetaMask/test-dapp/pull/315))
- feat: add get allowance support for ERC20 tokens ([#312](https://github.com/MetaMask/test-dapp/pull/312))
- Fix network status field ([#306](https://github.com/MetaMask/test-dapp/pull/306))
=> Release Candidate v8.6.0

src/index.js
Hi, I found the the `signPermit` test case is not following EIP-712 strictly so that Keystone won't able to pass this test case.
ref: https://eips.ethereum.org/EIPS/eip-712#definition-of-domainseparator:~:text=The%20EIP712Domain%20fields%20should%20be%20the%20order%20as%20above%2C%20skipping%20any%20absent%20fields.%20Future%20field%20additions%20must%20be%20in%20alphabetical%20order%20and%20come%20after%20the%20above%20fields.%20User%2Dagents%20should%20accept%20fields%20in%20any%20order%20as%20specified%20by%20the%20EIPT712Domain%20type
=> fix: make signPermit EIP712Domain following EIP-712

src/index.html, src/index.js
This PR adds support for SendEIP1559 transactions without suggested gas values.
This adds another flow for testing and fixes the issues encountered in certain network conditions, when gas values are high and the dapp suggested values are off, making tx's fail.
More context [here](https://consensys.slack.com/archives/C029JG63136/p1713175732692349?thread_ts=1712935151.911099&cid=C029JG63136).
https://github.com/MetaMask/test-dapp/assets/54408225/104b2d72-e82e-4a69-966d-532fe2e3ac75
1. Connect to the test dapp
2. Trigger a SendEIP1559 Without suggested gas tx
3. See gas is set to Market, instead of Dapp Suggested
=> feat: Add support for Send EIP1559 tx without suggested gas values

src/index.js
This changes the recipient address for the Queue transactions, to a malicious one, so queue tx's are flagged as malicious.
Context: this was identified by @sleepytanya in this issue https://github.com/MetaMask/metamask-mobile/issues/9272
https://github.com/MetaMask/test-dapp/assets/54408225/babfc800-cf31-4388-b0a4-7c63c6e8fa43
=> fix: queue malicious tx address

src/index.html, src/index.js
In this PR we add a couple of more functionalities for testing the PPOM feature:
- Added the ability to try Malicious Deeplinks for Mobile -> this has uncovered the following issue https://github.com/MetaMask/metamask-mobile/issues/9365
- Added a new section for Bypasses -> here we gather the identified bypasses for Blockaid. Now all of them are fixed except the **Malicious Permit with Padded ChainId**, but it is fixed in the next MM release, which contains the new ppom version https://github.com/MetaMask/metamask-extension/pull/24171
- Moved the Transfer/Approve with Odd Hex data to the Bypasses section -> this is done since they are better matching to this new section, as those were identified bypasses for Blockaid, opposed to the malformed transactions.
- Added a descriptive text for …
=> feat: add malicious deeplinks, bypasses and reorg

src/index.html, src/index.js
This PR adds a new identified bypass, where dapps could pass a value in hex, without the `0x` prefix, and this would make the validation fail - but the transaction will succeed.
This is now fixed in the current MM version 11.14, but it was happening in previous versions.
```
window.ethereum.sendAsync({
"method": "eth_sendTransaction",
"params": [
{
"from": "0x9A4834c232923d7Ff5F8F52741546E14097C2b24",
"to": "0xbD28258AD16776B34495323F21599761e47f4c8F",
"value": "ffffff" // see value without 0x
}
],
"timestamp": 1693229271999
}
)
```
https://github.com/MetaMask/test-dapp/assets/54408225/8dd578b4-b988-46c9-bf7d-f5cb21d3da62
1. Install an older version of the wallet ie MM version 11.12
2. Try the new bypass -- see the blockaid validation fails
3. Install 11.14 version of MM
4. Try the new …
=> feat: add Blockaid bypass for send value without 0x prefix

src/index.html, src/index.js
In this PR we add a section for displaying the contract address(es) for ERC721 and ERC1155 tokens, in the same way as we do for ERC20 tokens.
Taking the opportunity for consolidating a couple of titles, for the different tokens, so we always follow the same pattern.
ERC721 before
ERC721 now
========================================================
ERC1155 before
ERC1155 now
1. Deploy an ERC721 token --> see token address is displayed in the new section
2. Deploy a second ERC721 token --> see the two token addresses displayed in the new section
3. Deploy an ERC1155 token --> see token address is displayed in the new section
4. Deploy a second ERC1155 token --> see the two token addresses displayed in the new section
=> feat: add token contract addresses and consolidate names

src/index.css, src/index.html
Adds json rpc response text area for mobile json rpc method testing, [PR](https://github.com/MetaMask/metamask-mobile/pull/9356)
=> Adds json rpc result text area

CHANGELOG.md, package.json
This is the release candidate PR for `v8.8.0`.
- Add json RPC result text area ([#334](https://github.com/MetaMask/test-dapp/pull/334))
- Add token contract addresses and consolidate names ([#332](https://github.com/MetaMask/test-dapp/pull/332))
- Add SDK support ([#331](https://github.com/MetaMask/test-dapp/pull/331))
- Add Blockaid bypass for send value without 0x prefix ([#329](https://github.com/MetaMask/test-dapp/pull/329))
- Add malicious deeplinks, bypasses and reorg ([#328](https://github.com/MetaMask/test-dapp/pull/328))
- Change `eth-sig-util` to `@metamask/eth-sig-util` ([#286](https://github.com/MetaMask/test-dapp/pull/286))
=> Release candidate v8.8.0

src/connections.js, src/index.js
This PR addresses an issue occurring on Android within the Detox build, which prevents interaction with the test dapp. The problem first appeared in version v8.2.0, introduced in [PR #284](https://github.com/MetaMask/test-dapp/pull/284). The issue arises whenever @web3modal/ethers5 is imported, causing the tests to break. This behavior is observed exclusively on Android within the Detox build.
=> fix: android and detox E2E issue

CHANGELOG.md, package.json
This is the release candidate PR for `v8.9.0`.
- Add opBnB chain ([#335](https://github.com/MetaMask/test-dapp/pull/335))
- Fix issue with E2E tests failing on Android when running within Detox environment ([#343](https://github.com/MetaMask/test-dapp/pull/343))
- Fix yarn.lock syncing to remove unnecessary dependencies and improve package cleanliness ([#339](https://github.com/MetaMask/test-dapp/pull/339))
=> Release candidate v8.9.0

src/index.js
This is a fix for the watch all nfts and watch ERC1155 dapp actions, which should use provider (whichever is currently selected)
https://github.com/MetaMask/test-dapp/assets/54408225/5eb94872-dfe9-4a9f-84cc-de9a0b3a757f
=> fix: use provider for watch asset

package.json, yarn.lock
This PR bumps the MetaMask SDK version to 0.26.5 which features the new async protocol.
=> Bump MetaMask SDK version to 0.26.5

package.json, src/connections.js, src/index.js, yarn.lock
Previously upon checking if the extension is present via EIP6963 the dapp would perform `eth_accounts` and sync chainId but when using the SDK this conflicts as a connection might not exist at that point. This avoids that empty call if extension is not installed and the SDK is used.
=> [MMSDK] Updates mmsdk to latest and fixes a bad call when extension doesn't exist

src/index.html, src/index.js, src/onchain-sample-contracts.js
Adds a button Malicious Contract Interaction to the PPOM section
=> feat: Add malicious contract interaction as an option

CHANGELOG.md, package.json
- Add malicious contract interaction as an option ([#356](https://github.com/MetaMask/test-dapp/pull/356))
- Updates mmsdk to latest and fixes a bad call when extension doesn't exist ([#354](https://github.com/MetaMask/test-dapp/pull/354))
- Bump MetaMask SDK version to 0.26.5 ([#349](https://github.com/MetaMask/test-dapp/pull/349))
- Refactor permit code ([#351](https://github.com/MetaMask/test-dapp/pull/351))
- Fix the watch all nfts and watch ERC1155 dapp actions to use provider ([#348](https://github.com/MetaMask/test-dapp/pull/348))
=> Release Candidate v8.10.0

.eslintrc.js, src/index.html, src/index.js, src/signatures/utils.js
- Add signTypedData_v4 primaryType variants to test and assist development
- I lefted the verify signature out for now. We can add it upon request
- updated eslint to support nested .js modules
Fixes https://github.com/MetaMask/test-dapp/issues/358
Fixes https://github.com/orgs/MetaMask/projects/78/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C90948625%2C%22Linked+pull+requests%22%5D&filterQuery=-label%3Aepic+-status%3A%22%E2%9C%85+Done%22+-status%3A%22%E2%9D%8C+Won%27t+do%22+-is%3Apr+-label%3A%22area-documentation%22+test-dapp&pane=issue&itemId=81094156&issue=MetaMask%7CMetaMask-planning%7C3320
=> feat: Add SignTypedData primaryType variants: Blur - Order, PermitBatch, PermitSingle, Seaport - BulkOrder

src/components/signatures/permit-sign.js
Fixes the permit verification error from address missing
=> fix: permit message verification

CHANGELOG.md, package.json
This is the release candidate PR for `v9.0.0`
- Add SignTypedData primaryType variants: Blur - Order, PermitBatch, PermitSingle, Seaport - BulkOrder ([#376](https://github.com/MetaMask/test-dapp/pull/376))
- Move all components to separate files, use shared global state and events for updating cards based on connect / disconnect / deploy contract ([#379](https://github.com/MetaMask/test-dapp/pull/379))
=> Release Candidate v9.0.0

src/components/transactions/eip5792/sendCalls.js
Update default calls in `wallet_sendCalls` request.
- Reduce `value` to 1 Gwei and 0.5 Gwei.
- Use random address rather than malicious address for second call.
- Add `version` to request.
=> fix: update send calls default calls

CHANGELOG.md, package.json
This is the release candidate PR for v9.1.0.
- feat: add EIP-5792 section ([#388](https://github.com/MetaMask/test-dapp/pull/388))
- feat: add send with heavy hex data ([#386](https://github.com/MetaMask/test-dapp/pull/386))
- chore: updated icon ([#391](https://github.com/MetaMask/test-dapp/pull/391))
- fix: update send calls default calls ([#389](https://github.com/MetaMask/test-dapp/pull/389))
=> Release Candidate v9.1.0

src/components/ppom/batching.js, src/components/signatures/malformed-transactions.js, src/components/transactions/send.js, src/shared/constants.js
Probably due to a typo, the hardcoded gas limit on simple send flows was previously `0x5028` (20520 in decimal). This PR changes it to `0x5208` (21000 in decimal).
=> fix: Increase hardcoded gas limit

CHANGELOG.md, package.json
This is the release candidate PR for v9.2.0.
**Changed**
- Support updated send calls result ([#396](https://github.com/MetaMask/test-dapp/pull/396))
- chore: add workflow_dispatch to security-code-scanner ([#392](https://github.com/MetaMask/test-dapp/pull/392))
- Set yarn resolution for `elliptic@^6.6.1` ([#393](https://github.com/MetaMask/test-dapp/pull/393))
**Fixed**
- fix: Increase hardcoded gas limit ([#397](https://github.com/MetaMask/test-dapp/pull/397)
=> Release Candidate v9.2.0

src/components/transactions/eip5792/getCapabilities.js, src/components/transactions/eip5792/sendCalls.js
- Update `wallet_sendCalls` version to `2.0.0`.
- Add `atomicRequired` property to `wallet_sendCalls`.
- Add optional `Chain IDs` input to `wallet_getCapabilities`.
=> feat: support version 2.0.0 of EIP-5792

.github/workflows/build-lint-test.yml
The `build-lint-test` workflow uses the Ubuntu 20.04 image, which GitHub deprecated some time ago. Because of this new PRs will no longer pass CI. This commit upgrades the workflow to `ubuntu-latest` which should always work (and matches what we do in other repos).
=> Upgrade workflows to use ubuntu-latest

CHANGELOG.md, package.json
This is the release candidate PR for v9.3.0
- feat: support version 2.0.0 of EIP-5792 ([#402](https://github.com/MetaMask/test-dapp/pull/402))
=> Release candidate v9.3.0

src/components/ppom/batching.js, src/components/ppom/eip5792.js, src/components/ppom/index.js, src/components/ppom/sharedConstants.js, src/components/ppom/transactions.js, src/components/transactions/eip5792/sendCalls.js, src/index.js, src/onchain-sample-contracts.js, src/sample-addresses.js
This PR adds a new section for malicious batch transactions.
On each send call we'll have 1 type of a malicious transaction, the rest will be the 2 default simple sends (benign).
https://github.com/user-attachments/assets/b358e987-804a-4003-b69a-59e335f970b9
=> add: malicious send calls

src/components/connections/index.js, src/components/connections/networks-helpers.js, src/components/connections/networks.js, src/index.css, src/index.js
This PR adds a network picker to be able to switch networks from the dapp.
- If the network is already in the wallet, and we gave permissions to that network, it switches networks.
- If the network is already in the wallet, but we didn't give permissions to that network, it triggers the MM permissions dialog and then the network is switched
- If the network is not present in the wallet, we throw an error in the UI.
Future work:
- support addEtehreumChain for non-added networks, so we can add that network and then switch to it 
Main networks
Test networks
Happy Path
https://github.com/user-attachments/assets/ce85fb5c-71ff-4817-96be-8ae75316fa27
Error Handling
https://github.com/user-attachments/assets/ac7b7c74-32b3-4735-872c-3f907f36be5f
1. Connect to the test dapp
2. Give permissions to a …
=> feat: add network picker
