MetaMask/test-dapp

README.md, deploy.sh, package-lock.json, package.json
Fixes `@metamask/onboarding` import in test dapp, updates readme, and adds `static-server` for local testing.
=> Fix test-dapp, add static-server

.circleci/config.yml, .circleci/scripts/collect-har-artifact.sh, .circleci/scripts/deps-install.sh
This PR adds a basic CircleCI config.
=> Add simple CircleCI config

deploy.sh, index.html, metamask.css
This is sort of a combination of both #14 and #15
=> Use bootstrap styles in 3-column layout

.eslintrc.js, contract.js, package.json, yarn.lock
This PR updates the shared ESLint config to 2.0.0.
=> Update shared ESLint config

contract.js, index.html, metamask.css
- Moves logo to header
- Changes logo to front-facing fox SVG
- Cleans up some CSS
- Removes duplicate `Accounts:` section
=> Update header/logo; cleanup

.gitignore, deploy.sh, package.json, website/index.html
Publish the `@metamask/onboarding` bundle, don't break local serving.
=> Publish onboarding bundle

.eslintrc.js
Remove unnecessary properties from `eslintrc`
=> Remove eslint cruft

website/index.js
Listen for `chainChanged` instead of `chainIdChanged`, which was never a thing.
=> Listen for chainChanged, not chainIdChanged

package.json, prepare.sh, website/index.js
- Fix `[object Object]` error printout
- Move `prepare` commands into new file: `prepare.sh`
- Add `prepare` to `deploy` script
=> Update prepare script

src/index.css, src/index.html, src/index.js
- Adds encrypt/decrypt actions to test dapp
=> Add encrypt/decrypt actions

package.json
This version includes a new `personal_sign` button
=> Update `version` to v3.1.0

src/index.js
Huge thanks to @whymarrh for pointing out this out!
=> Removed Redundant isMetaMaskInstalled declaration

package.json, src/index.html, src/index.js
Current changes are printing the results of the test to console.
=> Migrating Signature examples

src/index.html, src/index.js
Adds a button for requesting `wallet_addEthereumChain` to the end of the UI. Adds the XDAI network, for arbitrary reasons.
=> Add addEthereumChain button

package.json, yarn.lock
Patch-bump `ethers` to help resolve security issue.
=> ethers@5.0.32

src/index.html, src/index.js
fixes https://github.com/MetaMask/test-dapp/issues/111
=> Add watch-asset button

src/index.js
Adding type `type: '0x0'` to legacy transaction.
=> Add type-0 to legacy transaction

src/index.js
Fix RPC URL and chainId for local Ganache instance. Screwed this up on the first PR 🤦
=> Fix RPC info for local Ganache instance

src/index.html, src/index.js
**Context**: on a previous PR, we added the Multisig Wallet bytecode and ABI. See: https://github.com/MetaMask/test-dapp/pull/207
**What**: here we add the frontend functionality for deploying a Multisig contract and Sending some ETH to its address
https://user-images.githubusercontent.com/54408225/216962360-66ce8c0a-c6b5-4951-974d-95d310347053.mp4
=> Adds Multisig deploy and Send to Multisig functions on the frontend

src/index.html, src/index.js
Introduces EIP 747 section to add an ERC20 token without having to deploy it first.
=> add section to watch a token

src/index.js
* Returns all accounts from `eth_accounts` instead of only the first 
[Ticket: mme-18515](https://github.com/MetaMask/metamask-extension/issues/18515)
=> return all accounts from `eth_accounts`

CHANGELOG.md, package.json
- Add optional URL parameter to scroll to an element on load ([#235](https://github.com/MetaMask/test-dapp/pull/235))
- Return all accounts in eth_accounts result ([#233](https://github.com/MetaMask/test-dapp/pull/233))
=> Release v6.2.0

src/index.js
=> fix: legacy send gas to 21000

CHANGELOG.md
- Implement EIP6963(Multi) provider detection ([#263](https://github.com/MetaMask/test-dapp/pull/263))
=> Release Candidate v7.3.0

src/index.js
Fixes PPOM section being enabled after account connection.
=> Enable PPOM section after connecting

CHANGELOG.md, package.json
This is the release candidate PR for v8.2.0
- Add Wallet Connect support ([#284](https://github.com/MetaMask/test-dapp/pull/284))
=> Release candidate v8.2.0

src/index.html, src/index.js
Small code improvements in the PPOM Sepolia support, as per review suggestion https://github.com/MetaMask/test-dapp/pull/298
This will help improve code readability.
No functional change is involved.
PPOM Sepolia support should continue to work as before.
=> adds ppom sepolia code improvements

src/onchain-sample-contracts.js
Add Base chain support for Blockaid.
=> Add Base network support.

src/onchain-sample-contracts.js
=> Fix: update NFT contract address.

src/index.js
In preparation of support additional permit types, refactoring the code a bit 
no UI/UX changes
=> refactor: Permit code

package.json
- Upgrade to yarn v1.22.22 (latest v1)
- dedupe lockfile
---
=> yarn v1.22.22

src/index.html, src/index.js
Adding NFT permit option to be able to write e2e test cases for it:
=> Adding NFT permit option

CHANGELOG.md, package.json
The release candidate add NFT permit option to test dapp.
https://github.com/MetaMask/test-dapp/pull/363
=> Release candidate for v8.11.0

src/index.js
The PR fixes issue with EIP-1559 transaction buttons not appearing in latest version of test dapp.
=> Fix enabling EIP-1559 support

CHANGELOG.md
The changelog entry for #362 was missing from release 8.11.0
=> chore: Add missing changelog entry

CHANGELOG.md, package.json
=> Release candidate for 8.12.0

package.json, yarn.lock
Updates the MetaMask SDK version to 0.30.1.
=> chore: bumps mmsdk to 0.30.1

CHANGELOG.md, package.json
Release candidate for version 8.13.0
=> chore: Release candidate for version 8.13.0

src/components/transactions/eip5792/sendCalls.js
Support new result object from `wallet_sendCalls` to automatically populate `wallet_getCallsStatus` input.
=> feat: support updated wallet_sendCalls result

CHANGELOG.md, package.json
This is the release candidate PR for v9.4.0
- Add malicious send calls ([#401](https://github.com/MetaMask/test-dapp/pull/401))
=> Release candidate v9.4.0
